/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace CryptoPaySubscription {
  export type SubscriptionStruct = {
    sender: AddressLike;
    receiver: AddressLike;
    token: AddressLike;
    amount: BigNumberish;
    interval: BigNumberish;
    nextPaymentTime: BigNumberish;
    active: boolean;
    totalPaid: BigNumberish;
    paymentCount: BigNumberish;
  };

  export type SubscriptionStructOutput = [
    sender: string,
    receiver: string,
    token: string,
    amount: bigint,
    interval: bigint,
    nextPaymentTime: bigint,
    active: boolean,
    totalPaid: bigint,
    paymentCount: bigint
  ] & {
    sender: string;
    receiver: string;
    token: string;
    amount: bigint;
    interval: bigint;
    nextPaymentTime: bigint;
    active: boolean;
    totalPaid: bigint;
    paymentCount: bigint;
  };
}

export interface CryptoPaySubscriptionInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "activate"
      | "activateWithPermit"
      | "cancelSubscription"
      | "createSubscription"
      | "executeSubscription"
      | "getSubscription"
      | "hasEnoughAllowance"
      | "isDue"
      | "nextSubscriptionId"
      | "owner"
      | "subscriptions"
      | "updateReceiver"
      | "updateSubscription"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "PaymentExecuted"
      | "ReceiverUpdated"
      | "SubscriptionCancelled"
      | "SubscriptionCreated"
      | "SubscriptionUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "activate",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "activateWithPermit",
    values: [
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelSubscription",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createSubscription",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "executeSubscription",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSubscription",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasEnoughAllowance",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "isDue", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "nextSubscriptionId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "subscriptions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateReceiver",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateSubscription",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "activate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "activateWithPermit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelSubscription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createSubscription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeSubscription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSubscription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasEnoughAllowance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isDue", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextSubscriptionId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "subscriptions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateReceiver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateSubscription",
    data: BytesLike
  ): Result;
}

export namespace PaymentExecutedEvent {
  export type InputTuple = [
    subscriptionId: BigNumberish,
    sender: AddressLike,
    receiver: AddressLike,
    amount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    subscriptionId: bigint,
    sender: string,
    receiver: string,
    amount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    subscriptionId: bigint;
    sender: string;
    receiver: string;
    amount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReceiverUpdatedEvent {
  export type InputTuple = [
    subscriptionId: BigNumberish,
    oldReceiver: AddressLike,
    newReceiver: AddressLike
  ];
  export type OutputTuple = [
    subscriptionId: bigint,
    oldReceiver: string,
    newReceiver: string
  ];
  export interface OutputObject {
    subscriptionId: bigint;
    oldReceiver: string;
    newReceiver: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubscriptionCancelledEvent {
  export type InputTuple = [subscriptionId: BigNumberish];
  export type OutputTuple = [subscriptionId: bigint];
  export interface OutputObject {
    subscriptionId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubscriptionCreatedEvent {
  export type InputTuple = [
    subscriptionId: BigNumberish,
    sender: AddressLike,
    receiver: AddressLike,
    token: AddressLike,
    amount: BigNumberish,
    interval: BigNumberish
  ];
  export type OutputTuple = [
    subscriptionId: bigint,
    sender: string,
    receiver: string,
    token: string,
    amount: bigint,
    interval: bigint
  ];
  export interface OutputObject {
    subscriptionId: bigint;
    sender: string;
    receiver: string;
    token: string;
    amount: bigint;
    interval: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubscriptionUpdatedEvent {
  export type InputTuple = [
    subscriptionId: BigNumberish,
    newAmount: BigNumberish,
    newInterval: BigNumberish
  ];
  export type OutputTuple = [
    subscriptionId: bigint,
    newAmount: bigint,
    newInterval: bigint
  ];
  export interface OutputObject {
    subscriptionId: bigint;
    newAmount: bigint;
    newInterval: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CryptoPaySubscription extends BaseContract {
  connect(runner?: ContractRunner | null): CryptoPaySubscription;
  waitForDeployment(): Promise<this>;

  interface: CryptoPaySubscriptionInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  activate: TypedContractMethod<
    [
      _receiver: AddressLike,
      _token: AddressLike,
      _initialAmount: BigNumberish,
      _recurringAmount: BigNumberish,
      _interval: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  activateWithPermit: TypedContractMethod<
    [
      _receiver: AddressLike,
      _token: AddressLike,
      _initialAmount: BigNumberish,
      _recurringAmount: BigNumberish,
      _interval: BigNumberish,
      _permitValue: BigNumberish,
      _permitDeadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  cancelSubscription: TypedContractMethod<
    [_subscriptionId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createSubscription: TypedContractMethod<
    [
      _receiver: AddressLike,
      _token: AddressLike,
      _amount: BigNumberish,
      _interval: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  executeSubscription: TypedContractMethod<
    [_subscriptionId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getSubscription: TypedContractMethod<
    [_subscriptionId: BigNumberish],
    [CryptoPaySubscription.SubscriptionStructOutput],
    "view"
  >;

  hasEnoughAllowance: TypedContractMethod<
    [_subscriptionId: BigNumberish],
    [boolean],
    "view"
  >;

  isDue: TypedContractMethod<
    [_subscriptionId: BigNumberish],
    [boolean],
    "view"
  >;

  nextSubscriptionId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  subscriptions: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint,
        bigint
      ] & {
        sender: string;
        receiver: string;
        token: string;
        amount: bigint;
        interval: bigint;
        nextPaymentTime: bigint;
        active: boolean;
        totalPaid: bigint;
        paymentCount: bigint;
      }
    ],
    "view"
  >;

  updateReceiver: TypedContractMethod<
    [_subscriptionId: BigNumberish, _newReceiver: AddressLike],
    [void],
    "nonpayable"
  >;

  updateSubscription: TypedContractMethod<
    [
      _subscriptionId: BigNumberish,
      _newAmount: BigNumberish,
      _newInterval: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "activate"
  ): TypedContractMethod<
    [
      _receiver: AddressLike,
      _token: AddressLike,
      _initialAmount: BigNumberish,
      _recurringAmount: BigNumberish,
      _interval: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "activateWithPermit"
  ): TypedContractMethod<
    [
      _receiver: AddressLike,
      _token: AddressLike,
      _initialAmount: BigNumberish,
      _recurringAmount: BigNumberish,
      _interval: BigNumberish,
      _permitValue: BigNumberish,
      _permitDeadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "cancelSubscription"
  ): TypedContractMethod<[_subscriptionId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createSubscription"
  ): TypedContractMethod<
    [
      _receiver: AddressLike,
      _token: AddressLike,
      _amount: BigNumberish,
      _interval: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "executeSubscription"
  ): TypedContractMethod<[_subscriptionId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getSubscription"
  ): TypedContractMethod<
    [_subscriptionId: BigNumberish],
    [CryptoPaySubscription.SubscriptionStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasEnoughAllowance"
  ): TypedContractMethod<[_subscriptionId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "isDue"
  ): TypedContractMethod<[_subscriptionId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "nextSubscriptionId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "subscriptions"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint,
        bigint
      ] & {
        sender: string;
        receiver: string;
        token: string;
        amount: bigint;
        interval: bigint;
        nextPaymentTime: bigint;
        active: boolean;
        totalPaid: bigint;
        paymentCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "updateReceiver"
  ): TypedContractMethod<
    [_subscriptionId: BigNumberish, _newReceiver: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateSubscription"
  ): TypedContractMethod<
    [
      _subscriptionId: BigNumberish,
      _newAmount: BigNumberish,
      _newInterval: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "PaymentExecuted"
  ): TypedContractEvent<
    PaymentExecutedEvent.InputTuple,
    PaymentExecutedEvent.OutputTuple,
    PaymentExecutedEvent.OutputObject
  >;
  getEvent(
    key: "ReceiverUpdated"
  ): TypedContractEvent<
    ReceiverUpdatedEvent.InputTuple,
    ReceiverUpdatedEvent.OutputTuple,
    ReceiverUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "SubscriptionCancelled"
  ): TypedContractEvent<
    SubscriptionCancelledEvent.InputTuple,
    SubscriptionCancelledEvent.OutputTuple,
    SubscriptionCancelledEvent.OutputObject
  >;
  getEvent(
    key: "SubscriptionCreated"
  ): TypedContractEvent<
    SubscriptionCreatedEvent.InputTuple,
    SubscriptionCreatedEvent.OutputTuple,
    SubscriptionCreatedEvent.OutputObject
  >;
  getEvent(
    key: "SubscriptionUpdated"
  ): TypedContractEvent<
    SubscriptionUpdatedEvent.InputTuple,
    SubscriptionUpdatedEvent.OutputTuple,
    SubscriptionUpdatedEvent.OutputObject
  >;

  filters: {
    "PaymentExecuted(uint256,address,address,uint256,uint256)": TypedContractEvent<
      PaymentExecutedEvent.InputTuple,
      PaymentExecutedEvent.OutputTuple,
      PaymentExecutedEvent.OutputObject
    >;
    PaymentExecuted: TypedContractEvent<
      PaymentExecutedEvent.InputTuple,
      PaymentExecutedEvent.OutputTuple,
      PaymentExecutedEvent.OutputObject
    >;

    "ReceiverUpdated(uint256,address,address)": TypedContractEvent<
      ReceiverUpdatedEvent.InputTuple,
      ReceiverUpdatedEvent.OutputTuple,
      ReceiverUpdatedEvent.OutputObject
    >;
    ReceiverUpdated: TypedContractEvent<
      ReceiverUpdatedEvent.InputTuple,
      ReceiverUpdatedEvent.OutputTuple,
      ReceiverUpdatedEvent.OutputObject
    >;

    "SubscriptionCancelled(uint256)": TypedContractEvent<
      SubscriptionCancelledEvent.InputTuple,
      SubscriptionCancelledEvent.OutputTuple,
      SubscriptionCancelledEvent.OutputObject
    >;
    SubscriptionCancelled: TypedContractEvent<
      SubscriptionCancelledEvent.InputTuple,
      SubscriptionCancelledEvent.OutputTuple,
      SubscriptionCancelledEvent.OutputObject
    >;

    "SubscriptionCreated(uint256,address,address,address,uint256,uint256)": TypedContractEvent<
      SubscriptionCreatedEvent.InputTuple,
      SubscriptionCreatedEvent.OutputTuple,
      SubscriptionCreatedEvent.OutputObject
    >;
    SubscriptionCreated: TypedContractEvent<
      SubscriptionCreatedEvent.InputTuple,
      SubscriptionCreatedEvent.OutputTuple,
      SubscriptionCreatedEvent.OutputObject
    >;

    "SubscriptionUpdated(uint256,uint256,uint256)": TypedContractEvent<
      SubscriptionUpdatedEvent.InputTuple,
      SubscriptionUpdatedEvent.OutputTuple,
      SubscriptionUpdatedEvent.OutputObject
    >;
    SubscriptionUpdated: TypedContractEvent<
      SubscriptionUpdatedEvent.InputTuple,
      SubscriptionUpdatedEvent.OutputTuple,
      SubscriptionUpdatedEvent.OutputObject
    >;
  };
}
